### ISSUE TITLE
Isn't it possible to pull application via mouse to other workspaces?

### ISSUE THREAD

**Issue by Bevor** [zakkak/workspace-grid#123]
Maybe this is related to #47.

There is an option "Wraparound workspaces when navigating" "...wrap to same for mouse scrolling?". I checked this option ( and I have 1 rows and 6 columns).
Does this option mean that I can pull applications or windows out of the current workspace into the next workspace as it worked on old Ubuntu versions before they messed it with Gnome3? 
If I try to pull an application out of the window to the next workspace, it spreads it to the half of the screen instead of moving it to the next screen.
I could get the expected result by selecting the desired application and then press CTRL + ALT + SHIFT + Cursor right or left. Then the application is moved to the workspace on the left or on the right. Shouldn't this work by pulling the application via mouse pointer to the next workspace as well?

**Comment by zakkak** [comment]
Hi @Bevor 

No, the behaviour you describe is the expected one. The option for wrapping around workspaces is just for when you change workspaces and you reach the last (either in its row or column).

I also suggest switching over to https://extensions.gnome.org/extension/1485/workspace-matrix/ since workspace-grid has been deprecated.
